# https://mcr.microsoft.com/en-us/product/devcontainers/php/about
FROM mcr.microsoft.com/devcontainers/php:8.2-apache-bookworm

LABEL maintainer="Visual Laravel (c) Tranzakt Project @ Github"

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install MariaDB client
RUN chmod +x /usr/local/bin/install-php-extensions && \
    apt-get update && export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y mariadb-client && \
    apt-get install -y postgresql-client && \
    apt-get install -y libpq-dev && \
    docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install mysqli pdo pgsql pdo_mysql pdo_pgsql && \
    install-php-extensions memcached-^3@stable && \
    install-php-extensions redis-^6@stable && \
    install-php-extensions mongodb-^1@stable && \
    apt-get -y autoremove && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

### TODO
# Configure Apache to point to the workspace directory and serve the public directory
# Test everything
