# https://mcr.microsoft.com/en-us/product/devcontainers/php/about
FROM mcr.microsoft.com/devcontainers/php:8.2-apache-bookworm

LABEL maintainer="Visual Laravel (c) Tranzakt Project @ Github"

ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_MAJOR=20

RUN mkdir -p /home/vscode/.vscode-server && chmod vscode:vscode /home/vscode/.vscode-server 

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Stable changes (cached so quick but less stable changes take less time to build)
# 1. Enable Apache mod_rewrite
# 2. Install MariaDB and Postgres command-line clients
# 3. Configure php extensions for Postgres, MySQL, Memcached, Redis and mongo
# 4. Install node, npm & bun
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load && \
    chmod +x /usr/local/bin/install-php-extensions && \
    apt-get update &&  \
    apt-get install -y mariadb-client && \
    apt-get install -y postgresql-client && \
    apt-get install -y libpq-dev && \
    docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install mysqli pdo pgsql pdo_mysql pdo_pgsql && \
    install-php-extensions memcached-^3@stable redis-^6@stable mongodb-^1@stable zip-^1@stable && \
    sudo apt-get install -y ca-certificates curl gnupg && sudo mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update &&  \
    apt-get install -y nodejs && \
    npm install -g bun

# Less stable changes
# 1. Install zsh enhancements
RUN # fzf appears to be missing and results in zsh completion errors && \
    git clone --depth 1 https://github.com/junegunn/fzf.git /tmp/fzf && /tmp/fzf/install && \
    git clone https://github.com/zsh-users/zsh-autosuggestions /home/vscode/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/vscode/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    sed -i -E 's/^plugins=\(git\)/# plugins=\(git\)\nplugins=\(git bun composer dirhistory gitfast laravel mongocli npm zsh-interactive-cd zsh-autosuggestions zsh-syntax-highlighting\)/' /home/vscode/.zshrc && \
    chown -R vscode:vscode /home/vscode 

# Experimental changes
RUN apt-get install -y fswatch

# Clean up (separate so that)
RUN apt-get -y autoremove && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

## TODO
# Make `apt-get install -y sqlitebrowser` work
