# https://mcr.microsoft.com/en-us/product/devcontainers/php/about
FROM mcr.microsoft.com/devcontainers/php:8.2-apache-bookworm

LABEL maintainer="Visual Laravel (c) Tranzakt Project @ Github"

ENV DEBIAN_FRONTEND=noninteractive

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# 1. Enable Apache mod_rewrite
# 2. Install bun
# 3. Install MariaDB and Postgres command-line clients
# 4. Configure php extensions for Postgres, MySQL, Memcached, Redis and mongo
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load && \
    curl -fsSL https://bun.sh/install | bash && \
    chmod +x /usr/local/bin/install-php-extensions && \
    apt-get update &&  \
    apt-get install -y mariadb-client && \
    apt-get install -y postgresql-client && \
    apt-get install -y libpq-dev && \
    docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install mysqli pdo pgsql pdo_mysql pdo_pgsql && \
    install-php-extensions memcached-^3@stable && \
    install-php-extensions redis-^6@stable && \
    install-php-extensions mongodb-^1@stable && \
    apt-get -y autoremove && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
