name: Codecov

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**.php'
      - '.github/workflows/codecov.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**.php'
      - '.github/workflows/codecov.yml'

defaults:
 run:
  working-directory: src

concurrency:
  group: "${{ github.workflow_ref }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  codecov:
    strategy:
      matrix:
        php-version: [8.3]
        os: [ubuntu-latest]
    runs-on: {{ matrix.os }}

    steps:
      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout
      - uses: actions/checkout@v4

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          composer validate --strict
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4.2.0
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            src/vendor
            src/node_modules
          key: vl-${{ matrix.os }}-php${{ matrix.php-version }}-${{ hashFiles('composer.json', 'composer.lock', 'package.json', 'package.lock') }}

      - name: Prepare Env.
        run: |
          # Copy .env, Generate key, Set directory permissions, Create empty SQLite DB
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          chmod -R 777 storage storage/database bootstrap/cache
          mkdir -p storage/database
          rm -f storage/database/visual-laravel.sqlite
          touch storage/database/visual-laravel.sqlite

      - name: Install Dependencies
        run: |
          composer self-update && composer install --no-interaction --no-progress --prefer-dist
          npm run build

      - name: Run coverage tests
        env:
          DB_CONNECTION: sqlite
        run: vendor/bin/phpunit --coverage-clover coverage.xml .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
