name: Laravel-Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'

    - name: Checkout
    - uses: actions/checkout@v4

    - name: Cache composer and npm
      uses: actions/cache@v4.2.0
      with:
        path: |
          vendor
          node_modules
        key: vl-${{ runner.os }}-${{ hashFiles('composer.json', 'composer.lock', 'package.json', 'package.lock') }}

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create empty database
      run: |
        mkdir -p storage
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/database/tests.sqlite
      run: php artisan test
